apiVersion: 1
datasources:
  - name: NetCore Prometheus
    uid: netcore-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: true
  - name: NetCore Loki
    uid: netcore-loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    editable: true
