# NetCore Control Room Operator profile config
# Keep this file private if it contains token = ...

[profiles.default]
api = "http://10.0.1.25:9010"
default_node = "SRV-M_TBS-01"
operator_id = "jan"
# token = "paste-token-here"
# token_file = "/etc/netcore-control-room/operator.token"

[profiles.event]
api = "http://10.0.1.25:9010"
default_node = "SRV-M_TBS-01"
operator_id = "event-lst"
token_file = "/etc/netcore-control-room/event-operator.token"
